---
#
# Playbook to install the ELK stack + Beats
#
#
- hosts: all
  remote_user: root
  become: yes
  become_user: root
  roles:
  - { role: ssh }
  - { role: java }
  - { role: elasticsearch }
  # - { role: ansible-elasticsearch }
  - { role: kibana }
  - { role: php }
  - { role: blockchain-git }
  - role: ansible-role-nvm
    nodejs_version: "10.16.0"
  - { role: blockchain-node-service }

